# Generated by Django 6.1 on 2026-08-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='hero/')),
                ('button_text', models.CharField(default='Read More', max_length=50)),
                ('button_url', models.CharField(default='#', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
