# Generated by Django 6.1 on 2026-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mandatory', '0002_newsticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='sajidxpgames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('sort_desc', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='sajidxpgames/')),
            ],
        ),
    ]
