# Generated by Django 6.1 on 2026-08-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mandatory', '0003_sajidxpgames'),
    ]

    operations = [
        migrations.AddField(
            model_name='sajidxpgames',
            name='url_name',
            field=models.CharField(default='home', max_length=50),
        ),
    ]
